defaults:
  - base_agent
  - data_source: swe_bench
  - llm: gpt-3.5-turbo-16k
  - retrieval: bm25
  # Graph
  - graph: collect_edit
  - graph/context_collector: llm_retrieval
  - graph/editor: simple_editor
  # Backbone
  - backbone: openai-gpt-3.5-turbo
  - backbone/prompt: simple_agent

  - tools@tools.acr_search_class: acr_search_class
  - tools@tools.acr_search_method_in_file: acr_search_method_in_file
  - tools@tools.acr_search_method_in_class: acr_search_method_in_class
  - tools@tools.acr_search_method: acr_search_method
  - tools@tools.acr_search_code: acr_search_code
  - tools@tools.acr_search_code_in_file: acr_search_code_in_file
  # Other tools
  - _self_

chat_prompt:
  owner_repo_commit: "hwchase17/openai-tools-agent"

graph:
  editor:
    edit_prompt:
      owner_repo_commit: "jbr-code-editing/edit"
  context_collector:
    search_prompt:
      owner_repo_commit: "jbr-code-editing/search-reviewed"

retrieval:
  splitter:
    _target_: "langchain.text_splitter.RecursiveCharacterTextSplitter"
    chunk_size: 512
    chunk_overlap: 128
    add_start_index: true
