defaults:
  - base_eval
  - data_source: swe_bench
  - extractor: full_file
  - _self_

input_path: outputs/inference.jsonl # <--- Change this to the path of the inference file
metrics:
  code_bert_score:
    _target_: "code_editing.metrics.CodeBertScoreMetric"
  code_bert_score_file:
    _target_: "code_editing.metrics.CodeBertScoreFileMetric"
  weak_format:
    _target_: "code_editing.metrics.FormatAdherenceWeak"
  is_not_nan:
    _target_: "code_editing.metrics.SuccessfulGeneration"
  valid_git_diff:
    _target_: "code_editing.metrics.ValidGitDiff"
  gpt4_eval:
    _target_: "code_editing.metrics.GPT4EvaluationMetric"
    limit_count: 10
  chrf:
    _target_: "code_editing.metrics.ChrfMetric"
  chrf_file:
    _target_: "code_editing.metrics.ChrfFileMetric"
  exact_match:
    _target_: "code_editing.metrics.ExactMatchMetric"
  file_localization:
    _target_: "code_editing.metrics.FileEditLocalizationMetric"
    add_sample_metrics: true
  line_localization:
    _target_: "code_editing.metrics.LineEditLocalizationMetric"
    add_sample_metrics: true
  py_scope_localization:
    _target_: "code_editing.metrics.PyScopeEditLocalizationMetric"
    add_sample_metrics: true
  file_view_localization:
    _target_: "code_editing.metrics.FileViewLocalizationMetric"
    add_sample_metrics: true
  line_view_localization:
    _target_: "code_editing.metrics.LineViewLocalizationMetric"
    add_sample_metrics: true
  py_scope_view_localization:
    _target_: "code_editing.metrics.PyScopeViewLocalizationMetric"
    add_sample_metrics: true
  total_context:
    _target_: "code_editing.metrics.TotalContextMetric"
    add_sample_metrics: true
  swebench:
    _target_: "code_editing.metrics.SWEBenchMetric"
    max_workers: 32

wandb:
  project: lca-code-editing
  enable: true
