name: Test & Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9
    - uses: Gr1N/setup-poetry@v8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry export --output requirements.txt
        pip install -r requirements.txt
    - name: Lint with isort
      run: |
        isort --profile black .
    - name: Lint with Black
      run: |
        black . --check -l 120
#    - name: Lint with mypy
#      run: |
#        mypy .
    - name: Run unit tests with pytest
      run: |
        pytest
